### ISSUE TITLE
Check redirect location in auth response to determine auth success

### ISSUE THREAD

**Issue by TechnikEmpire** [TechnikEmpire/Citadel-Windows#33]
We need to inspect the location header when we get a redirect response during auth and determine auth success based on whether or not the listed location is the login route or not.

**Comment by dkwiebe** [comment]
Would it be better to use a different authentication system on the server that would provide feedback in the response rather than setting up redirects?  That's what we're working on for our own integration with 3rd party systems.

**Comment by TechnikEmpire** [comment]
These are solved already just not closed here because your guys branch is much further ahead than mine. I need to merge back in from you guys at some point.

**Comment by TechnikEmpire** [comment]
If we did change this then we need to modify the redirect if authenticated code to provide feedback when it detects a client rather than redirect. This is a bit of a hack at the moment but it's stable.

**Comment by dkwiebe** [comment]
If it's stable then let's leave it until we are running out of work. 😃
